<div class="container">
 <div class="page-header">
     <h1>Crea tu Ensalada</h1>
     <h2>Vive la experiencia BajaSalads</h2>
 </div>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#paso1">Paso 1</a></li>
    <li><a data-toggle="tab" href="#paso2">Paso 2</a></li>
    <li><a data-toggle="tab" href="#paso3">Paso 3</a></li>
    <li><a data-toggle="tab" href="#paso4">Paso 4</a></li>
    <li><a data-toggle="tab" href="#paso5">Paso 5</a></li>
  </ul>
  <div class="row">
    <div class="col-xs-12 col-md-6">
        <div class="tab-content">
            <div id="paso1" class="tab-pane fade in active">
          <h3>Tamaño</h3>
            <div class="alert alert-info fade in" id="alert_inicial">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Información! </strong>Una vez seleccionado el siguiente paso no podrás cambiar tu tamaño de orden.
            </div>

            <select onChange="calcularCalorias()" id="porciones" class="image-picker show-labels show-html">
                  <option value="nada">nada</option>
                  <option id="chico"  data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="300" data-img-src="img/crea_ensalada/chico.png" value="chico">Chico</option>
                  <option id="mediano" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal ="500"data-img-src="img/crea_ensalada/mediano.png" value="mediano" >Mediano</option>
                  <option id="grande" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal ="600"data-img-src="img/crea_ensalada/grande.png" value="grande">Grande</option>
            </select>
          <input type="button" class="btn btn-primary btnSiguientevalid" value="Siguiente"  />

          </div>
          <div id="paso2" class="tab-pane fade">
          <h3>Pollos y Mariscos</h3> 
            <select id="pollos_mariscos" onChange="calcularCalorias()" class="image-picker show-labels limit_callback show-html" multiple="multiple">
                  <option value="nada">nada</option>
                  <option id="1" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/pollo1.jpg" value="1">Asado</option>
                  <option id="2" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/pollo2.jpg" value="2">Picoso</option>
                  <option id="3" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/pollo1.jpg" value="3">BBQ</option>
                  <option id="4" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/pollo2.jpg" value="4">Búfalo</option>
                   <option id="5" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/pollo1.jpg" value="5">Parmesano</option>
                  <option id="6" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/pollo2.jpg" value="6">Otro</option>
                  <option id="7" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/pollo1.jpg" value="7">Atún</option>
                  <option id="8" data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/marisco2.jpg" value="8">Surimi</option>
                  <option id="9"  data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/marisco1.jpg" value="9">Cute Kitten </option>
            </select>
            <input type="button" class="btn btn-primary btnSiguientevalid" value="Siguiente" />
         </div>
    <div id="paso3" class="tab-pane fade">
    <h3>Barra fría</h3>
          <select id="barra_fria" onChange="calcularCalorias()" class="image-picker show-labels limit_callback show-html"  multiple="multiple">
              <option value="nada">nada</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_1.jpg" value="1">Mango</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_2.jpg" value="2">Uva</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_3.jpg" value="3">Manzana</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_4.jpg" value="4">Plátano</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_5.jpg" value="5">Sandía</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_1.jpg" value="6">Mango</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_2.jpg" value="7">Uva</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_3.jpg" value="8">Manzana</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_4.jpg" value="9">Plátano</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_5.jpg" value="10">Sandía</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_1.jpg" value="11">Mango</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_2.jpg" value="12">Uva</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_3.jpg" value="13">Manzana</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_4.jpg" value="14">Plátano</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_5.jpg" value="15">Sandía</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_1.jpg" value="16">Mango</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_2.jpg" value="17">Uva</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_3.jpg" value="18">Manzana</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_4.jpg" value="19">Plátano</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_5.jpg" value="20">Sandía</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_1.jpg" value="21">Mango</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/img_2.jpg" value="22">Uva</option>    
        </select>
         <a class="btn btn-primary btnAtras">Atras</a>
         <a class="btn btn-primary btnSiguiente">Siguiente</a>
    </div>
    <div id="paso4" class="tab-pane fade">
    <h3>Aderezos</h3> 
     <select id="aderezos" onChange="calcularCalorias()" class="image-picker show-labels limit_callback show-html" multiple="multiple">
              <option value="nada">nada</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="1">Ranch</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="2">Chipotle</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="3">Cilantro</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="4">Mil islas</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="5">César</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="6">Vinagreta</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="7">Italiano</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="8">Aceite de Oliva</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/aderezo.png" value="9">Mostaza miel</option>
    </select>
        <a class="btn btn-primary btnAtras">Atras</a>
        <input type="button" class="btn btn-primary btnSiguiente" value="Siguiente"  />
    </div>
    <div id="paso5" class="tab-pane fade">
    <h3>Croutones</h3>
        
        <select id="extras" onChange="calcularCalorias()" class="image-picker show-labels limit_callback show-htm" multiple="multiple">
             <option value="nada">nada</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/croutones.png" value="1">Croutones</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20" data-img-src="img/crea_ensalada/croutones.png" value="2">Sopita</option>
        </select>
        <h3>Bebidas</h3>
         <select id="bebidas" onChange="calcularCalorias()" class="image-picker show-labels limit_callback show-htm" multiple="multiple">
              <option value="nada">nada</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/coca.jpg" value="1">Coca cola lata</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/coca2.jpg" value="2">Coca 600ml</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/fanta.jpg" value="3">Fanta lata</option> 
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/peper.jpg" value="4">Peper</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/pepsi.jpg" value="5">Pepsi</option>
              <option data-calfat="5" data-fat="8" data-satfat="7" data-chol="5" data-sod="2" data-carbo="3" data-fiber="9" data-sugar="5" data-protein="3" data-transfat="4" data-cal="20"  data-img-src="img/crea_ensalada/sprite.jpg" value="6">Sprite</option> 
        </select>
        <a class="btn btn-primary btnAtras">Atras</a>
        <button type="button" class="btn btn-success btn-compra" ><span class="glyphicon glyphicon-shopping-cart"></span> Añadir al carrito</button>
    </div>
      </div>
   </div>
    <div class="col-xs-12 col-md-6">
    <h3>Información Nutrimental.</h3>
    <table class="table table-striped table-bordered">
        <thead>
             <tr>
                 <th class="text-center">Porción</th>
                 <th class="text-center">Valor</th>
             </tr>
         </thead>
         <tbody>
              <tr>
                 <td>Cal</td>
                 <td id="cal">0g</td>
              </tr>
              <tr>
                 <td>Cal/Fat</td>
                 <td id="calfat">0g</td>
              </tr>
              <tr>
                 <td>Fat</td>
                 <td id="fat">0g</td>
              </tr>
              <tr>
                 <td>SatFat</td>
                 <td id="satfat">0g</td>
              </tr>
              <tr>
                 <td>Chol</td>
                 <td id="chol">0g</td>
              </tr>
              <tr>
                 <td>Sod</td>
                 <td id="sod">0g</td>
              </tr>
              <tr>
                 <td>Carbo.</td>
                 <td id="carbo">0g</td>
              </tr>
              <tr>
                 <td>Fiber</td>
                 <td id="fiber">0g</td>
              </tr>
              <tr>
                 <td>Sugar</td>
                 <td id="sugar">0g</td>
              </tr>
              <tr>
                 <td>Protein</td>
                 <td id="protein">0g</td>
              </tr>
              <tr>
                 <td>TransFat</td>
                 <td id="transfat">0g</td>
              </tr>
         </tbody>
        </table>
      </div>
 </div>
</div>